[package]
name = "keeb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hidapi = "1.2.5"
strum = "0.24"
strum_macros = "0.24"
keeb_lib = {path = "./keeb_lib"}
gmmk = {path = "./gmmk"}
